
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - node_modules
      - .yarn-cache
    volumes:
      - /home/cache:/cache

  install:
    image: node:8.2.1
    commands:
      - node --version
      - npm --version
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile
      - yarn cache dir

  lint:
    image: node:8.2.1
    group: frontend
    commands:
      - ./tasks/lint.sh

  test:
    image: node:8.2.1
    group: frontend
    commands:
      - ./tasks/test.sh

  test-page:
    image: node:8.2.1
    group: frontend
    commands:
      - ./tasks/test-page.sh

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - node_modules
      - .yarn-cache
    volumes:
      - /home/cache:/cache
